ALTER TABLE `livrable` ADD `source` text DEFAULT 'local' NOT NULL;--> statement-breakpoint
ALTER TABLE `livrable` ADD `drive_file_id` text;--> statement-breakpoint
ALTER TABLE `project` ADD `drive_listing_origin` text;--> statement-breakpoint
CREATE UNIQUE INDEX `livrable_project_id_drive_file_id_unique` ON `livrable` (`project_id`,`drive_file_id`) WHERE "livrable"."drive_file_id" is not null;--> statement-breakpoint
-- HAND-WRITTEN COMMENT, not generated by drizzle-kit: keep it if this migration is ever regenerated.
-- Story 5.3 (AD-14): assumes no conversation already has two livrables (checked on the local DB on 2026-10-02).
CREATE UNIQUE INDEX `livrable_conversation_id_unique` ON `livrable` (`conversation_id`) WHERE "livrable"."conversation_id" is not null;