import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { drizzle } from 'drizzle-orm/node-sqlite';

// `node:sqlite` is Node's native SQLite binding — no native compilation
// step (unlike `better-sqlite3`), which is why the architecture spine
// pins it for round 1. The file lives outside version control (see
// .gitignore) so each machine gets its own local database.
const sqlite = new DatabaseSync('./db/local.db');

// `node:sqlite` disables foreign-key enforcement per connection by
// default (SQLite's own default). APP_STATE.activeProjectId is declared
// as a FK to PROJECT.id — enable enforcement so that stays a real
// guarantee, not just documentation.
sqlite.exec('PRAGMA foreign_keys = ON');

export const db = drizzle({ client: sqlite });

// Round 1 has no separate deploy/migrate step (single process, single
// machine — see AGENTS.md/architecture spine): applying pending
// migrations generated by `npm run db:generate` on module load keeps a
// fresh `db/local.db` (or a freshly cloned repo) working the moment
// `npm run dev`/`next build` starts, with no manual `db:push` first.
//
// This applies each `db/migrations/<name>/migration.sql` directly via
// the raw `node:sqlite` connection rather than
// `drizzle-orm/node-sqlite/migrator`'s `migrate()`: that helper calls a
// `stmt.setReturnArrays` method this Node version's `node:sqlite` does
// not implement (`TypeError: stmt.setReturnArrays is not a function`),
// so it cannot run here. Applied migrations are tracked in
// `__schema_migrations` (bespoke, not drizzle's own bookkeeping table)
// so this stays idempotent across restarts.
const MIGRATIONS_DIR = './db/migrations';

sqlite.exec(
  'CREATE TABLE IF NOT EXISTS __schema_migrations (name TEXT PRIMARY KEY)',
);

const alreadyApplied = new Set(
  (sqlite.prepare('SELECT name FROM __schema_migrations').all() as {
    name: string;
  }[]).map((row) => row.name),
);

const pendingMigrations = existsSync(MIGRATIONS_DIR)
  ? readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
      .filter(
        (entry) =>
          entry.isDirectory() &&
          existsSync(join(MIGRATIONS_DIR, entry.name, 'migration.sql')),
      )
      .map((entry) => entry.name)
      .sort()
      .filter((name) => !alreadyApplied.has(name))
  : [];

for (const name of pendingMigrations) {
  const sql = readFileSync(
    join(MIGRATIONS_DIR, name, 'migration.sql'),
    'utf8',
  );
  sqlite.exec('BEGIN');
  try {
    for (const statement of sql.split('--> statement-breakpoint')) {
      const trimmed = statement.trim();
      if (trimmed) sqlite.exec(trimmed);
    }
    sqlite.prepare('INSERT INTO __schema_migrations (name) VALUES (?)').run(name);
    sqlite.exec('COMMIT');
  } catch (error) {
    sqlite.exec('ROLLBACK');
    // `pendingMigrations` is computed once, before this loop opens any
    // transaction — if another OS process (e.g. a bundler's worker pool)
    // raced this one and already applied the same migration against the
    // same fresh `db/local.db`, SQLite reports "already exists" rather
    // than letting both succeed. That is only a non-failure if the whole
    // migration truly landed elsewhere: `ROLLBACK` just undid every
    // statement *this* transaction ran, so if a *later* statement is the
    // one that collided, the earlier statements never re-ran and must be
    // verified, not assumed, before this migration is marked applied.
    const message = error instanceof Error ? error.message : String(error);
    if (/already exists/i.test(message)) {
      const targets = [
        ...sql.matchAll(/CREATE\s+(?:TABLE|INDEX|UNIQUE INDEX)\s+`(\w+)`/gi),
      ].map((match) => match[1]);
      const allObjectsExist = targets.every(
        (target) =>
          sqlite
            .prepare(
              "SELECT 1 FROM sqlite_master WHERE name = ? AND type IN ('table', 'index')",
            )
            .get(target) !== undefined,
      );
      if (allObjectsExist) {
        sqlite
          .prepare(
            'INSERT OR IGNORE INTO __schema_migrations (name) VALUES (?)',
          )
          .run(name);
        continue;
      }
    }
    throw error;
  }
}
