import { existsSync, readdirSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { drizzle } from 'drizzle-orm/node-sqlite';

// `node:sqlite` is Node's native SQLite binding — no native compilation
// step (unlike `better-sqlite3`), which is why the architecture spine
// pins it for round 1. The file lives outside version control (see
// .gitignore) so each machine gets its own local database.
//
// `timeout` (SQLite busy timeout, ms): `next build` evaluates route
// handler modules (Story 5.1's `app/api/google/oauth/*`) in several
// worker processes at once to collect their configuration. On a fresh
// `db/local.db` they all run the migrations below concurrently, and
// without a busy timeout the losers fail immediately with "database is
// locked" instead of waiting their turn for the migration lock below.
const sqlite = new DatabaseSync('./db/local.db', { timeout: 30000 });

// `node:sqlite` disables foreign-key enforcement per connection by
// default (SQLite's own default). APP_STATE.activeProjectId is declared
// as a FK to PROJECT.id — enable enforcement so that stays a real
// guarantee, not just documentation.
sqlite.exec('PRAGMA foreign_keys = ON');

export const db = drizzle({ client: sqlite });

// Round 1 has no separate deploy/migrate step (single process, single
// machine — see AGENTS.md/architecture spine): applying pending
// migrations generated by `npm run db:generate` on module load keeps a
// fresh `db/local.db` (or a freshly cloned repo) working the moment
// `npm run dev`/`next build` starts, with no manual `db:push` first.
//
// This applies each `db/migrations/<name>/migration.sql` directly via
// the raw `node:sqlite` connection rather than
// `drizzle-orm/node-sqlite/migrator`'s `migrate()`: that helper calls a
// `stmt.setReturnArrays` method this Node version's `node:sqlite` does
// not implement (`TypeError: stmt.setReturnArrays is not a function`),
// so it cannot run here. Applied migrations are tracked in
// `__schema_migrations` (bespoke, not drizzle's own bookkeeping table)
// so this stays idempotent across restarts.
const MIGRATIONS_DIR = './db/migrations';

// Story 5.1: `next build` evaluates the OAuth route handler modules in
// several worker processes at once, and on a fresh `db/local.db` every
// one of them used to compute its own pending list and race the others
// (losers failed with "database is locked", or "table already exists"
// on a migration whose created objects no longer all exist afterwards,
// e.g. drizzle's `__new_*` table-rebuild pattern). The whole run now
// happens under one write lock taken *before* reading which migrations
// are applied (`BEGIN IMMEDIATE`, with the busy timeout above): a process
// that waited for the lock sees the winner's bookkeeping and has nothing
// left to apply.
const migrationNames = existsSync(MIGRATIONS_DIR)
  ? readdirSync(MIGRATIONS_DIR, { withFileTypes: true })
      .filter(
        (entry) =>
          entry.isDirectory() &&
          existsSync(join(MIGRATIONS_DIR, entry.name, 'migration.sql')),
      )
      .map((entry) => entry.name)
      .sort()
  : [];

sqlite.exec('BEGIN IMMEDIATE');
try {
  sqlite.exec(
    'CREATE TABLE IF NOT EXISTS __schema_migrations (name TEXT PRIMARY KEY)',
  );
  const alreadyApplied = new Set(
    (sqlite.prepare('SELECT name FROM __schema_migrations').all() as {
      name: string;
    }[]).map((row) => row.name),
  );

  for (const name of migrationNames) {
    if (alreadyApplied.has(name)) continue;
    const sql = readFileSync(
      join(MIGRATIONS_DIR, name, 'migration.sql'),
      'utf8',
    );
    for (const statement of sql.split('--> statement-breakpoint')) {
      const trimmed = statement.trim();
      if (trimmed) sqlite.exec(trimmed);
    }
    sqlite.prepare('INSERT INTO __schema_migrations (name) VALUES (?)').run(name);
  }
  sqlite.exec('COMMIT');
} catch (error) {
  // SQLite may already have rolled back on its own (e.g. disk full); a
  // ROLLBACK then would throw and hide the original migration error.
  if (sqlite.isTransaction) sqlite.exec('ROLLBACK');
  throw error;
}
