ALTER TABLE `document` ADD `drive_file_id` text;--> statement-breakpoint
ALTER TABLE `document` ADD `mime_type` text;--> statement-breakpoint
ALTER TABLE `document` ADD `origin` text;--> statement-breakpoint
ALTER TABLE `document` ADD `used_as_context` integer DEFAULT false NOT NULL;--> statement-breakpoint
CREATE UNIQUE INDEX `document_project_id_drive_file_id_unique` ON `document` (`project_id`,`drive_file_id`) WHERE "document"."drive_file_id" is not null;--> statement-breakpoint
-- HAND-WRITTEN BACKFILL, not generated by drizzle-kit: keep it if this migration is ever regenerated.
-- FR-4 / Story 5.7: documents added outside the drive are always used as context.
UPDATE `document` SET `used_as_context` = 1 WHERE `source` = 'manual';
